[package]
name = "fusb302b"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { version = "1.4.3", default-features = false }
embedded-hal = "0.2.7"
fugit = "0.3.6"
log = "0.4.17"
paste = "1.0.12"
proc-bitfield = "0.2.2"
