[package]
name = "usb-pd"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-bitfield = "0.2.4"
byteorder = { version = "1.4.3", default-features = false }
defmt = "0.3.5"
fugit = "0.3.7"
heapless = { version = "0.7.16", features = ["defmt-impl"] }
